import Link from "next/link";
import { Logo } from "@/components/Logo";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service — Chronova AI",
};

const SECTIONS = [
  {
    title: "1. Accepting these terms",
    body: [
      "By creating a Chronova account or using the app, you agree to these terms. If you're using Chronova on behalf of a school or institution, you're agreeing on its behalf as well as your own.",
    ],
  },
  {
    title: "2. What Chronova is",
    body: [
      "Chronova is an AI-powered academic scheduling tool. It helps you build a study schedule, chat with an AI Academic Mentor, track exams and progress, and — for institutions — generate timetables.",
      "Free to start, no credit card required for the student tier described on our homepage.",
    ],
  },
  {
    title: "3. Your account",
    body: [
      "You're responsible for keeping your login credentials secure and for all activity under your account.",
      "You must provide accurate information (like your real sleep hours and subjects) — Chronova's suggestions are only as good as the information you give it.",
      "You must be old enough to legally use an online service in your country, or have a parent/guardian's involvement if not.",
    ],
  },
  {
    title: "4. Acceptable use",
    body: [
      "Don't use Chronova to harass, mislead, or harm others.",
      "Don't try to scrape, reverse-engineer, or overload the service.",
      "Don't use the AI Academic Mentor to generate content unrelated to your studies that violates the law or these terms.",
    ],
  },
  {
    title: "5. AI-generated content",
    body: [
      "Schedules, study tips, and revision plans generated by the AI Academic Mentor are suggestions, not guarantees. Chronova doesn't guarantee any particular academic outcome, grade, or exam result.",
      "Always use your own judgment — especially for anything involving your health (sleep, breaks, workload).",
    ],
  },
  {
    title: "6. Institution accounts",
    body: [
      "Institution Portal accounts can create batches, teachers, classrooms, and generated timetables for their organization. Institutions are responsible for the accuracy of the data they upload and for their own compliance with applicable education and privacy regulations.",
    ],
  },
  {
    title: "7. Termination",
    body: [
      "You can stop using Chronova and delete your account at any time from Settings. We may suspend or terminate accounts that violate these terms.",
    ],
  },
  {
    title: "8. Disclaimer & limitation of liability",
    body: [
      "Chronova is provided \"as is.\" We work hard to keep it accurate and available, but we don't guarantee it will be error-free or uninterrupted.",
      "To the extent permitted by law, Chronova isn't liable for indirect or consequential damages arising from your use of the app.",
    ],
  },
  {
    title: "9. Changes to these terms",
    body: [
      "We may update these terms as the product evolves. Continued use after an update means you accept the revised terms.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh" }} className="page-bg animate-fade">
      <div className="page-content">
        <header style={{ height: "64px", display: "flex", alignItems: "center", borderBottom: "1px solid var(--c-border-1)" }}>
          <div className="container" style={{ display: "flex", alignItems: "center", justifyContent: "space-between", width: "100%" }}>
            <Link href="/" style={{ display: "flex", alignItems: "center", textDecoration: "none" }}>
              <Logo size={24} />
            </Link>
            <Link href="/" className="btn btn-ghost" style={{ fontSize: "12.5px", fontWeight: 500, padding: "6px 10px" }}>
              <ArrowLeft size={13} style={{ marginRight: "4px" }} /> Back to home
            </Link>
          </div>
        </header>

        <main className="container-sm" style={{ padding: "56px var(--sp-6) 80px" }}>
          <p className="eyebrow">Legal</p>
          <h1 className="font-display" style={{ fontSize: "32px", fontWeight: 600, letterSpacing: "-0.02em", color: "var(--c-text-primary)", marginTop: "8px" }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: "13px", color: "var(--c-text-secondary)", marginTop: "8px" }}>
            Last updated: September 2026
          </p>
          <p style={{ fontSize: "14px", color: "var(--c-text-secondary)", lineHeight: 1.7, marginTop: "20px" }}>
            These terms cover how you can use Chronova AI. They're written in plain language on purpose —
            if anything's unclear, email us and we'll clarify.
          </p>

          <div style={{ display: "flex", flexDirection: "column", gap: "28px", marginTop: "36px" }}>
            {SECTIONS.map(({ title, body }) => (
              <section key={title}>
                <h2 className="font-display" style={{ fontSize: "17px", fontWeight: 600, color: "var(--c-text-primary)", marginBottom: "10px" }}>
                  {title}
                </h2>
                <ul style={{ display: "flex", flexDirection: "column", gap: "8px", paddingLeft: "18px" }}>
                  {body.map((line, i) => (
                    <li key={i} style={{ fontSize: "13.5px", color: "var(--c-text-secondary)", lineHeight: 1.65 }}>
                      {line}
                    </li>
                  ))}
                </ul>
              </section>
            ))}

            <section className="card" style={{ padding: "20px", marginTop: "8px" }}>
              <h2 className="font-display" style={{ fontSize: "17px", fontWeight: 600, color: "var(--c-text-primary)", marginBottom: "8px" }}>
                10. Contact
              </h2>
              <p style={{ fontSize: "13.5px", color: "var(--c-text-secondary)", lineHeight: 1.65 }}>
                Questions about these terms? Email us at{" "}
                <a href="mailto:support@chronova.ai" style={{ color: "var(--c-accent-dark)", textDecoration: "underline" }}>
                  support@chronova.ai
                </a>.
              </p>
            </section>
          </div>
        </main>

        <footer style={{ borderTop: "1px solid var(--c-border-1)", padding: "24px 0", background: "var(--c-surface-0)" }}>
          <div className="container" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "16px" }}>
            <Logo size={20} />
            <div style={{ display: "flex", gap: "4px" }}>
              <Link href="/privacy" className="btn btn-ghost" style={{ fontSize: "12px", padding: "4px 8px", fontWeight: 500 }}>Privacy</Link>
              <Link href="/terms" className="btn btn-ghost" style={{ fontSize: "12px", padding: "4px 8px", fontWeight: 500 }}>Terms</Link>
              <a href="mailto:support@chronova.ai" className="btn btn-ghost" style={{ fontSize: "12px", padding: "4px 8px", fontWeight: 500 }}>Contact</a>
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
}
